name: NewCommands
version: 1.2
main: de.ghac.newcommands.NewCommands
author: ghac
website: www.ghac.de
commands:
  newcommands:
    description: 'Information about NewCommands plugin'
    usage: /<command>
    aliases: [nc]
  permissions:
   newcommands.reload:
     description: 'Reload - Command'
     default: false
   newcommands.list:
     description: 'List - Command'
     default: false